### PR TITLE
Issue #1082

### PR DESCRIPTION
**Pull request by jcuanm**
Fixed the 'none' problem

### CODE REVIEW

**Comment by horak** [comment]
hey @jcuanm, just let me know when this is ready to be merged. It would also be helpful for documentation purposes if you could expound a little on what "the 'none' problem is". Nice job making your commit messages more diverse!

**Comment by horak** [comment]
bump^

**Comment by jcuanm** [comment]
The 'none' problem was happening because we were checking for the variable 'none' and not the string "none". I put an if...else statement that fixed the issue. Everything should be good to go.

**Comment by jcuanm** [comment]
For some reason, this merge does not show up on production.

**Comment by horak** [comment]
Still not?

**Comment by jcuanm** [comment]
That was an old comment. It's working fine now!

**Comment by horak** [comment]
cool!

**Pull request merged**
