### PR TITLE
added retweet filter

### LINKED ISSUE #629: Add filter for retweets
Currently, re-tweets are returned along with the original item. This can lead to a large amount of the same tweet. Should add a way to filter.

### PR DESCRIPTION
**Pull request by ebensing**
using the new exlude API, retweet filter adds an exclude for things with
"RT" in them. fixes #629

### CODE REVIEW

**Comment by nickkapur** [comment]
@ebensing Is there no way to get this over to the right next to the sort menu? Otherwise this looks good!

**Comment by nickkapur** [comment]
Is there no way to get this over to the right, next to the sort menu. Otherwise it looks good!

**Comment by nickkapur** [comment]
This looks ready to go!

**Comment by ebensing** [comment]
I'm going to go ahead and merge this in. @corinnecurcie I recommend you take a look at the changes, as this is how you add new parameters to the search.

**Pull request merged**
